import { RenderManagerService } from '@univerjs/engine-render';
import { get_univer } from './src/lib/server/univer.ts';
import { SheetsRenderService } from '@univerjs/preset-sheets-core';

const { univer_api, univer } = await get_univer();
const workbook = univer_api.createWorkbook({
	id: 'dP7QpnJuY8RWyGfWBR4z4',
	sheetOrder: ['1', '2'],
	name: 'tes(8)',
	appVersion: '0.10.10',
	locale: 'enUS',
	styles: {
		'0': {
			fs: 10,
			cl: { rgb: '#000000FF' },
			vt: 3,
			tb: 2,
			td: 0,
			ff: 'Arial',
			it: 0,
			bl: 0,
			bd: {},
		},
		'1': { ht: 2, td: 0, ff: 'Arial', it: 0, bl: 0, bd: {} },
		'2': { td: 0, ff: 'Comfortaa', it: 0, bl: 0, bd: {} },
		'3': { fs: 12, td: 0, ff: 'Arial', it: 0, bl: 0, bd: {} },
		'4': { td: 0, ff: 'Arial', it: 1, bl: 0, bd: {} },
		'5': { td: 0, ff: 'Arial', it: 0, bl: 1, bd: {} },
		'6': { td: 0, ff: 'Arial', it: 0, bl: 0, bd: {}, ul: { s: 1, t: 12 } },
		'7': { td: 0, ff: 'Arial', it: 0, bl: 0, bd: {}, st: { s: 1, t: 12 } },
		'8': { bg: { rgb: '#FF0000FF' }, td: 0, ff: 'Arial', it: 0, bl: 0, bd: {} },
		'9': { cl: { rgb: '#FF0000FF' }, td: 0, ff: 'Arial', it: 0, bl: 0, bd: {} },
		'10': { ht: 3, vt: 2, td: 0, ff: 'Arial', it: 0, bl: 0, bd: {} },
		'11': { vt: 2, td: 0, ff: 'Arial', it: 0, bl: 0, bd: {} },
		'12': { vt: 1, td: 0, ff: 'Arial', it: 0, bl: 0, bd: {} },
		'13': { ff: 'Arial', it: 0, bl: 1, bd: {} },
		'14': { td: 0, tr: { a: 45, v: 0 }, ff: 'Arial', it: 0, bl: 0, bd: {} },
		'15': {
			cl: { rgb: '#0000FFFF' },
			td: 0,
			it: 0,
			bl: 0,
			bd: {},
			ul: { s: 1, t: 12 },
		},
		'16': { ff: 'Comfortaa', it: 0, bl: 0, bd: {} },
		'17': { fs: 12, ff: 'Arial', it: 0, bl: 0, bd: {} },
		'18': { ff: 'Arial', it: 1, bl: 0, bd: {} },
		'19': { ff: 'Arial', it: 0, bl: 0, bd: {}, ul: { s: 1, t: 12 } },
		'20': { ff: 'Arial', it: 0, bl: 0, bd: {}, st: { s: 1, t: 12 } },
		'21': { bg: { rgb: '#FF0000FF' }, ff: 'Arial', it: 0, bl: 0, bd: {} },
		'22': { cl: { rgb: '#FF0000FF' }, ff: 'Arial', it: 0, bl: 0, bd: {} },
		'23': { tb: 3, td: 0, ff: 'Arial', it: 0, bl: 0, bd: {} },
		'24': { tb: 2, td: 0, ff: 'Arial', it: 0, bl: 0, bd: {} },
		'25': { td: 0, tr: { a: -45, v: 0 }, ff: 'Arial', it: 0, bl: 0, bd: {} },
		'26': { td: 0, ff: 'Arial', it: 0, bl: 0, bd: {} },
		'27': {
			cl: { rgb: '#0000FFFF' },
			td: 0,
			it: 0,
			bl: 0,
			bd: {
				l: { s: 13, cl: { rgb: '#FF0000FF' } },
				r: { s: 13, cl: { rgb: '#FF0000FF' } },
				t: { s: 13, cl: { rgb: '#FF0000FF' } },
				b: { s: 13, cl: { rgb: '#FF0000FF' } },
			},
			ul: { s: 1, t: 12 },
		},
		'28': { td: 0, tr: { a: -90, v: 0 }, ff: 'Arial', it: 0, bl: 0, bd: {} },
		'29': { td: 0, tr: { a: 90, v: 0 }, ff: 'Arial', it: 0, bl: 0, bd: {} },
		'30': {
			td: 0,
			ff: 'Arial',
			it: 0,
			bl: 0,
			bd: { l: { s: 1, cl: { rgb: '#000000FF' } } },
		},
		'31': {
			td: 0,
			ff: 'Arial',
			it: 0,
			bl: 0,
			bd: { r: { s: 1, cl: { rgb: '#000000FF' } } },
		},
		'32': {
			td: 0,
			ff: 'Arial',
			it: 0,
			bl: 0,
			bd: { t: { s: 1, cl: { rgb: '#000000FF' } } },
		},
		'33': {
			td: 0,
			ff: 'Arial',
			it: 0,
			bl: 0,
			bd: { b: { s: 1, cl: { rgb: '#000000FF' } } },
		},
		'34': { td: 0, ff: 'Arial', it: 0, bl: 0, bd: {} },
		'35': { ff: 'Arial', it: 0, bl: 0, bd: {} },
		'36': {
			td: 0,
			ff: 'Arial',
			it: 0,
			bl: 0,
			bd: {},
			n: { pattern: 'yyyy-mm-dd' },
		},
		'37': { fs: 17, td: 0, ff: 'Arial', it: 0, bl: 0, bd: {} },
		PfmtjK: { td: 0, tr: { a: -90, v: 0 }, ff: 'Arial', it: 0, bl: 0 },
	},
	sheets: {
		'1': {
			id: '1',
			name: 'Sheet1',
			tabColor: '',
			hidden: 0,
			showGridlines: 1,
			freeze: { xSplit: 1, ySplit: 7, startRow: 6, startColumn: 0 },
			defaultColumnWidth: 102,
			defaultRowHeight: 22,
			mergeData: [
				{ startColumn: 2, startRow: 7, endColumn: 2, endRow: 8 },
				{ startColumn: 4, startRow: 7, endColumn: 5, endRow: 7 },
				{ startColumn: 4, startRow: 10, endColumn: 5, endRow: 12 },
			],
			cellData: {
				'0': {
					'0': { t: 1, v: 'center', s: '1' },
					'3': { t: 1, v: 'font', s: '2' },
					'4': { t: 1, v: 'font', s: '3' },
					'5': { t: 1, v: 'it', s: '4' },
					'6': { t: 1, v: 'bold', s: '5' },
					'7': { t: 1, v: 'under', s: '6' },
					'8': { t: 1, v: 'strike', s: '7' },
					'9': { t: 1, v: 'back', s: '8' },
					'10': { t: 1, v: 'fore', s: '9' },
				},
				'1': {
					'0': { t: 1, v: 'vert-middle', s: '10' },
					'1': {
						p: {
							id: '__INTERNAL_EDITOR__DOCS_NORMAL',
							documentStyle: {
								marginTop: 0,
								marginBottom: 2,
								marginLeft: 2,
								marginRight: 2,
								pageSize: { width: 106.58333206176758, height: null },
								renderConfig: {
									horizontalAlign: 0,
									verticalAlign: 2,
									centerAngle: 0,
									vertexAngle: 0,
									wrapStrategy: 0,
									zeroWidthParagraphBreak: 1,
								},
							},
							body: {
								dataStream: 'bold italic test\r\n',
								textRuns: [
									{ st: 0, ed: 2, ts: { bl: 1, it: 0, ff: 'Arial' } },
									{
										st: 2,
										ed: 4,
										ts: { bl: 1, it: 0, ff: 'Arial', st: { s: 1, t: 12 } },
									},
									{
										st: 4,
										ed: 5,
										ts: { bl: 0, it: 0, ff: 'Arial', st: { s: 1, t: 12 } },
									},
									{
										st: 5,
										ed: 8,
										ts: { bl: 0, it: 1, ff: 'Arial', st: { s: 1, t: 12 } },
									},
									{
										st: 8,
										ed: 10,
										ts: {
											bl: 0,
											it: 1,
											ff: 'Arial',
											ul: { s: 1, t: 12 },
											st: { s: 1, t: 12 },
										},
									},
									{
										st: 10,
										ed: 11,
										ts: { bl: 0, it: 1, ff: 'Arial', ul: { s: 1, t: 12 } },
									},
									{
										st: 11,
										ed: 12,
										ts: { bl: 0, it: 0, ff: 'Arial', ul: { s: 1, t: 12 } },
									},
									{
										st: 12,
										ed: 14,
										ts: {
											bl: 0,
											it: 0,
											fs: 16,
											ff: 'Arial',
											ul: { s: 1, t: 12 },
										},
									},
									{
										st: 14,
										ed: 16,
										ts: {
											bl: 0,
											it: 0,
											fs: 16,
											ff: 'Arial',
											cl: { rgb: '#FF9900FF' },
										},
									},
								],
							},
						},
						s: '11',
					},
					'3': { t: 1, v: 'family', s: '2' },
					'4': { t: 1, v: 'size', s: '3' },
					'5': { t: 1, v: 'alic', s: '4' },
					'6': { t: 1, v: 'test', s: '5' },
					'7': { t: 1, v: 'line', s: '6' },
					'8': { t: 1, v: 'through', s: '7' },
					'9': { t: 1, v: 'ground', s: '8' },
					'10': { t: 1, v: 'ground', s: '9' },
				},
				'2': {
					'0': { t: 1, v: 'vert-top', s: '12' },
					'3': { t: 1, v: 'test', s: '2' },
					'4': { t: 1, v: 'test', s: '3' },
					'5': { t: 1, v: 'test', s: '4' },
					'6': { t: 2, v: null, s: '13' },
					'7': { t: 1, v: 'test', s: '6' },
					'8': { t: 1, v: 'test', s: '7' },
					'9': { t: 1, v: 'test', s: '8' },
					'10': { t: 1, v: 'test', s: '9' },
				},
				'3': {
					'0': { t: 1, v: '45 deg rot', s: '14' },
					'1': {
						p: {
							id: '__INTERNAL_EDITOR__DOCS_NORMAL',
							documentStyle: {
								marginTop: 0,
								marginBottom: 2,
								marginLeft: 2,
								marginRight: 2,
								pageSize: { width: null, height: null },
								renderConfig: {
									horizontalAlign: 0,
									verticalAlign: 0,
									centerAngle: 0,
									vertexAngle: 0,
									wrapStrategy: 0,
									zeroWidthParagraphBreak: 1,
								},
							},
							body: {
								dataStream: 'link\r\n',
								customRanges: [
									{
										rangeId: '7Ox4tMQ0sVwiamOnwfqJ3',
										rangeType: 0,
										startIndex: 0,
										endIndex: 4,
										properties: { url: 'https://example.com/' },
									},
								],
							},
						},
						s: '15',
					},
					'3': { t: 2, v: null, s: '16' },
					'4': { t: 2, v: null, s: '17' },
					'5': { t: 2, v: null, s: '18' },
					'6': { t: 2, v: null, s: '13' },
					'7': { t: 2, v: null, s: '19' },
					'8': { t: 2, v: null, s: '20' },
					'9': { t: 2, v: null, s: '21' },
					'10': { t: 2, v: null, s: '22' },
				},
				'4': {
					'0': { t: 1, v: 'wrap', s: '23' },
					'3': { t: 2, v: null, s: '16' },
					'4': { t: 2, v: null, s: '17' },
					'5': { t: 2, v: null, s: '18' },
					'6': { t: 2, v: null, s: '13' },
					'7': { t: 2, v: null, s: '19' },
					'8': { t: 2, v: null, s: '20' },
					'9': { t: 2, v: null, s: '21' },
					'10': { t: 2, v: null, s: '22' },
				},
				'5': {
					'0': { t: 1, v: 'clip', s: '24' },
					'3': { t: 2, v: null, s: '16' },
					'4': { t: 2, v: null, s: '17' },
					'5': { t: 2, v: null, s: '18' },
					'6': { t: 2, v: null, s: '13' },
					'7': { t: 2, v: null, s: '19' },
					'8': { t: 2, v: null, s: '20' },
					'9': { t: 2, v: null, s: '21' },
					'10': { t: 2, v: null, s: '22' },
				},
				'7': { '6': { t: 1, v: 'up', s: '25' } },
				'8': { '6': { t: 1, v: 'down', s: '14' } },
				'9': { '6': { t: 1, v: 'vertical down', s: '26' } },
				'10': {
					'2': {
						p: {
							id: '__INTERNAL_EDITOR__DOCS_NORMAL',
							documentStyle: {
								marginTop: 0,
								marginBottom: 2,
								marginLeft: 2,
								marginRight: 2,
								pageSize: { width: null, height: null },
								renderConfig: {
									horizontalAlign: 0,
									verticalAlign: 0,
									centerAngle: 0,
									vertexAngle: 0,
									wrapStrategy: 0,
									zeroWidthParagraphBreak: 1,
								},
							},
							body: {
								dataStream: 'all borders\r\n',
								customRanges: [
									{
										rangeId: 'CUP88MCXVp0aTDUww_TIQ',
										rangeType: 0,
										startIndex: 0,
										endIndex: 11,
										properties: { url: '#gid=1&range=E11:F13' },
									},
								],
							},
						},
						s: '27',
					},
					'6': { t: 1, v: 'straight up', s: 'PfmtjK' },
				},
				'11': { '6': { t: 1, v: 'straight down', s: '29' } },
				'12': { '2': { t: 1, v: 'left border', s: '30' } },
				'14': { '2': { t: 1, v: 'right border', s: '31' } },
				'16': { '2': { t: 1, v: 'top border', s: '32' } },
				'18': { '2': { t: 1, v: 'bottom border', s: '33' } },
				'22': { '12': { t: 1, v: 'test', s: '34' } },
				'24': { '2': { t: 2, v: 1, s: '34' } },
				'25': { '2': { t: 2, v: 2, s: '34' } },
				'26': {
					'0': { t: 1, v: 'test', s: '34' },
					'2': { t: 2, v: 3, s: '34' },
				},
				'27': {
					'0': { t: 1, v: 'test', f: '=A27', s: '35', si: null },
					'2': { t: 2, v: 6, f: '=SUM(C24:C27)', s: '35', si: null },
				},
				'28': {
					'0': {
						p: {
							id: '__INTERNAL_EDITOR__DOCS_NORMAL',
							documentStyle: {
								marginTop: 0,
								marginBottom: 2,
								marginLeft: 2,
								marginRight: 2,
								pageSize: { width: null, height: null },
								renderConfig: {
									horizontalAlign: 0,
									verticalAlign: 0,
									centerAngle: 0,
									vertexAngle: 0,
									wrapStrategy: 0,
									zeroWidthParagraphBreak: 1,
								},
							},
							body: {
								dataStream: 'TRUE\r\n',
								customRanges: [
									{
										rangeId: 't27wDQshsJefJRDp-Dqwu',
										rangeType: 0,
										startIndex: 0,
										endIndex: 4,
										properties: { url: '#gid=2&range=A1' },
									},
								],
							},
						},
						s: '15',
					},
				},
				'29': { '0': { t: 3, v: 0, s: '34' } },
				'30': { '0': { t: 2, v: 45658, s: '36' } },
			},
			rightToLeft: 0,
			columnData: {},
			rowData: { '3': { h: 82.76, ia: 0 } },
			rowCount: 1000,
			columnCount: 20,
			zoomRatio: 1.6,
			scrollTop: 0,
			scrollLeft: 0,
			rowHeader: { width: 46, hidden: 0 },
			columnHeader: { height: 20, hidden: 0 },
		},
		'2': {
			id: '2',
			name: 'Sheet2',
			tabColor: '',
			hidden: 0,
			showGridlines: 1,
			freeze: { xSplit: 0, ySplit: 0, startRow: -1, startColumn: -1 },
			defaultColumnWidth: 102,
			defaultRowHeight: 22,
			mergeData: [],
			cellData: {
				'0': { '1': { t: 1, v: 'wtf', s: '34' } },
				'2': { '0': { t: 1, v: 'test', s: '37' } },
				'5': {},
			},
			rightToLeft: 0,
			columnData: {
				'0': { hd: 0, w: 804.61 },
				'1': { hd: 0, w: 25.28 },
				'2': { hd: 1 },
			},
			rowData: { '0': { h: 85.9, ia: 0 }, '5': { hd: 1 } },
			rowCount: 1000,
			columnCount: 20,
			zoomRatio: 1,
			scrollTop: 0,
			scrollLeft: 0,
			rowHeader: { width: 46, hidden: 0 },
			columnHeader: { height: 20, hidden: 0 },
		},
	},
	resources: [
		{ name: 'SHEET_RANGE_PROTECTION_PLUGIN', data: '' },
		{ name: 'SHEET_AuthzIoMockService_PLUGIN', data: '{}' },
		{ name: 'SHEET_WORKSHEET_PROTECTION_PLUGIN', data: '{}' },
		{ name: 'SHEET_WORKSHEET_PROTECTION_POINT_PLUGIN', data: '{}' },
		{ name: 'SHEET_HYPER_LINK_PLUGIN', data: '{"1":[]}' },
		{ name: 'SHEET_DEFINED_NAME_PLUGIN', data: '' },
		{ name: 'SHEET_RANGE_THEME_MODEL_PLUGIN', data: '{}' },
	],
	custom: {
		recalc: {
			'1': {
				rows: [
					0, 1, 2, 4, 5, 7, 8, 9, 10, 11, 12, 14, 16, 18, 22, 24, 25, 26, 27,
					28, 29, 30,
				],
				cols: [0, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 12],
			},
			'2': { rows: [2, 5], cols: [2] },
		},
	},
});

const sheet = workbook.getActiveSheet();

console.log(sheet.getSheetName());
console.log(workbook.save().sheets[1].rowData);

console.log(sheet.getRowHeight(10));

sheet.autoResizeRows(10, 1);
console.log(workbook.save().sheets[1].rowData);

const skeleton = sheet.getSkeleton();
console.log(univer.__getInjector().get(SheetsRenderService));
